// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class RestoreMembershipRate_DiscountRateValues : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RestoreMembershipRate_DiscountRateValues));
        
        string IMigrationMetadata.Id
        {
            get { return "201808042326484_RestoreMembershipRate_DiscountRateValues"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
